services:
  - type: web
    name: flash-detection-app
    env: python
    buildCommand: apt-get update && apt-get install -y ffmpeg libsm6 libxext6 && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true 